# -*- coding: utf-8 -*-
"""pcaimage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bixbicPBUDp8rGynwVNLj6YWMaQCjmPK
"""

import numpy as np

import matplotlib.image as mpimg 
import matplotlib.pyplot as plt

img = mpimg.imread(r'D:\bird11.png')

print(img.shape) 
plt.axis('off') 
plt.imshow(img)

img_r = np.reshape(img, (445,1884))
print(img_r.shape)

from sklearn.decomposition import PCA

ipca = PCA(n_components=50).fit(img_r)
img_c = ipca.transform(img_r)

print(img_c.shape) 
print(np.sum(ipca.explained_variance_ratio_))

#Percentage of variance explained by each of the selected components.

temp = ipca.inverse_transform(img_c) 
print(temp.shape)

temp = np.reshape(temp,(445,628, 3)) 
print(temp.shape)

plt.axis('off') 
plt.imshow(temp)



from sklearn.decomposition import PCA

ipca = PCA(n_components=445).fit(img_r)
img_c = ipca.transform(img_r)

var = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp_ = np.reshape(temp,(445,628, 3)) 
#_________________________________________________________
ipca = PCA(n_components=1).fit(img_r)
img_c = ipca.transform(img_r)

var01 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp01 = np.reshape(temp,(445,628, 3)) 


#_________________________________________________________
ipca = PCA(n_components=3).fit(img_r)
img_c = ipca.transform(img_r)

var02 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp02 = np.reshape(temp,(445,628, 3)) 



#_________________________________________________________

ipca = PCA(n_components= 5).fit(img_r)
img_c = ipca.transform(img_r)

var03 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp03 = np.reshape(temp,(445,628, 3)) 




#_________________________________________________________

ipca = PCA(n_components=10).fit(img_r)
img_c = ipca.transform(img_r)

var04 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp04 = np.reshape(temp,(445,628, 3)) 


#_________________________________________________________

ipca = PCA(n_components=20).fit(img_r)
img_c = ipca.transform(img_r)

var05 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp05 = np.reshape(temp,(445,628, 3)) 



#_________________________________________________________

ipca = PCA(n_components=30).fit(img_r)
img_c = ipca.transform(img_r)

var06 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp06 = np.reshape(temp,(445,628, 3)) 



#_________________________________________________________
ipca = PCA(n_components=40).fit(img_r)
img_c = ipca.transform(img_r)

var07 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp07= np.reshape(temp,(445,628, 3)) 

ipca = PCA(n_components=64).fit(img_r)
img_c = ipca.transform(img_r)

var08 = np.sum(ipca.explained_variance_ratio_)

temp = ipca.inverse_transform(img_c) 

temp08 = np.reshape(temp,(445,628, 3))

print('\033[1m' +"\nPercentage of variance explained by \n","1 component = ",var01,"\t3 components = ",var02,"\t5 components = ",var03," "+ '\033[0m')
print('\033[1m' +"\n 10 components = ",var04,"\t 20 components = ",var05,"\t 30 components = ",var06," "+ '\033[0m')
print('\033[1m' +"\n 40 components = ",var07,"\t 64 components = ",var08,"\t 445 components = ",var," "+ '\033[0m')


plt.figure(figsize=(15,15))

plt.subplot(3,3,1)
plt.axis('off')
plt.imshow(temp01)

plt.subplot(3,3,2)
plt.axis('off')
plt.imshow(temp02)

plt.subplot(3,3,3)
plt.axis('off')
plt.imshow(temp03)

plt.subplot(3,3,4)
plt.axis('off')
plt.imshow(temp04)

plt.subplot(3,3,5)
plt.axis('off')
plt.imshow(temp05)

plt.subplot(3,3,6)
plt.axis('off')
plt.imshow(temp06)

plt.subplot(3,3,7)
plt.axis('off')
plt.imshow(temp07)

plt.subplot(3,3,8)
plt.axis('off')
plt.imshow(temp08)

plt.subplot(3,3,9)
plt.axis('off')
plt.imshow(temp_)

